<script src="{{url('custom')}}/vendor/jquery/jquery.min.js"></script>
<script src="{{url('custom')}}/vendor/popper.js/umd/popper.min.js"> </script>
<script src="{{url('custom')}}/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="{{url('custom')}}/vendor/jquery.cookie/jquery.cookie.js"> </script>
{{-- <script src="{{url('custom')}}/vendor/chart.js/Chart.min.js"></script> --}}
<script src="{{url('custom')}}/vendor/jquery-validation/jquery.validate.min.js"></script>
{{-- <script src="{{url('custom')}}/js/charts-home.js"></script> --}}
<script src="{{url('custom')}}/js/front.js"></script>
<script src="{{url('custom.js')}}"></script>
